### ISSUE TITLE
Submit to Asset Library

### ISSUE THREAD

**Issue by Wavesonics** [zmarcos/godothreadpool#1]
I was just looking for exactly this, would be great have it in the asset library for people to find!

**Comment by zmarcos** [comment]
You are absolutely right!
Wasn't sent yet, because there is one feature that is missing, a way to retrieve finished tasks.
Fear no more, I will be working on it.

**Comment by zmarcos** [comment]
ThreadPool was officially published on Godot Asset Library.
Asset link: https://godotengine.org/asset-library/asset/556
