### ISSUE TITLE
Using thread_pool.gd as an autoload causes Parse Error

### ISSUE THREAD

**Issue by EdGeber** [zmarcos/godothreadpool#10]
Assigning `thread_pool.gd` as an autoload with name `ThreadPool` causes Godot to disable the plugin and show the following error message: `res://addons/thread_pool/thread_pool.gd:1 - Parse Error: The class "ThreadPool" conflicts with the AutoLoad singleton of the same name, and is therefore redundant. Remove the class_name declaration to fix this error.`

**Comment by zmarcos** [comment]
Godot doesn't like that name anymore. 😞
You have to workaround using another name, like `GlobalThreadPool`.

![godot_auto_tp1](https://github.com/zmarcos/godothreadpool/assets/17889472/e036da02-6e98-462b-a5cc-362188abbe41)
