### ISSUE TITLE
Return a Future object to allow waiting on results

### ISSUE THREAD

**Issue by Wavesonics** [zmarcos/godothreadpool#2]
It would be great if `submit_task` returned an object that could be waited on.

The use case is to submit a bunch of tasks, store all of the returned Futures in an array, then iterate the array calling something like `future.get()` on each which should wait for the task to finish, and then return the result from it.

```GDScript
	var results := []
	
	var future = $ThreadPool.submit_task_array_parameterized(self, "background_exe", [1])
	results.push_back(future)
	
	future = $ThreadPool.submit_task_array_parameterized(self, "background_exe", [2])
	results.push_back(future)
	
	
	for result in results:
		var x = result.get()
		print(x)
	
	print("All tasks complete!")
```

**Comment by zmarcos** [comment]
I really like Futures, was thinking about them for many days.
The thing is, that waiting for them on the main thread leads to lag. Well, today the programmer can make a loop with fetch_finished_tasks() and happily kill app responsiveness.

Waiting for Futures on another thread in the pool can lead to locking the pool, thus the entire process.

Right now, the ThreadPool design favors using signals, but if some people avoid signals, then the pool is awkward to use.

I am aiming for a new pool design with Futures, with the following features:

- Futures need additional atomic primitives, they can be expensive if you have many short-lived tasks. If you have few long-lived tasks, the costs should be negligible. Be prepared to pay the price.

- Users can wait for Futures on any thread, not afraid of locking the app.

- Signals are going away.

**Comment by Wavesonics** [comment]
Ah totally understandable. The library is already a really great asset for GDScript!

I made a PR (_Feel free to not accept it, but I thought it might help someone in a similar situation to me_) that makes the Task object behave like a Future. I really do need to stall the main thread and wait to collect the results, so for me it's worth it.

**Comment by Wavesonics** [comment]
Example of #3 in action:
```GDScript
	var tasks := []
	# Process each pipe individually
	for pipe in pipes:
		var task = $ThreadPool.submit_task_unparameterized(pipe, "fluid_tick", TASK_TAG)
		tasks.push_back(task)
	
	# Wait for all pipes to finish
	for task in tasks:
		var result = task.wait_for_result()
```

**Comment by zmarcos** [comment]
In the future, do you see yourself in need of canceling a Future?

@Wavesonics , do you need to cancel a Future?

**Comment by Wavesonics** [comment]
In a generalized implementation for sure! But for my use case I never need to.

**Comment by zmarcos** [comment]
Cancelling should fit easily into the code.

Talking about features, don't expect a `get_or_wait_until(100millisec)` anytime soon.

**Comment by zmarcos** [comment]
A new thread pool was developed to solve this issue, **FutureThreadPool**, commit ff371908820919b3ac9498685b665d8ea5ac6c5f. Fetch functions were removed, and signals changed. When submitting a task, now you receive a future instead, but every else should work the same way.

A new release will occur when having documentation for the new thread pool.
