### ISSUE TITLE
Cannot run FutureThreadPool

### ISSUE THREAD

**Issue by tavurth** [zmarcos/godothreadpool#4]
```gdscript
func test(a):
  print(a)

func _ready():
	var p = FutureThreadPool.new()
	print(p.submit_task(self, "test", "TEST"))
```

<img width="408" alt="Screenshot 2022-02-22 at 18 50 19" src="https://user-images.githubusercontent.com/100964/155168510-92745edb-8645-42e0-93bc-98cbf0a6989b.png">

**Comment by tavurth** [comment]
This seems to be because I was running it from inside a reference? 🤔

**Comment by zmarcos** [comment]
When submitting a task, you have to make sure the object exists at the time the of call (that is, in the future).
You can only **free** it after execution.

**Comment by zmarcos** [comment]
I believe the issue was solved.
