### ISSUE TITLE
ObjectDB instances leaked at exit in Godot 3.5.x

### ISSUE THREAD

**Issue by sirmike** [zmarcos/godothreadpool#7]
Hi, I'm using your addon in Godot 3.5.x and I've stumbled upon a problem. Due to a bug in Godot, code which references inner classes causes a leak when exiting a program:

```
Godot Engine v3.5.2.stable.custom_build.170ba337a - https://godotengine.org
OpenGL ES 3.0 Renderer: NVIDIA GeForce RTX 3080/PCIe/SSE2
Async. shader compilation: OFF
 
ERROR: Condition "_first != nullptr" is true.
   at: SelfList<class GDScriptFunction>::List::~List (.\core/self_list.h:108) - Condition "_first != nullptr" is true.
ERROR: Condition "_first != nullptr" is true.
   at: SelfList<class GDScript>::List::~List (.\core/self_list.h:108) - Condition "_first != nullptr" is true.
WARNING: ObjectDB instances leaked at exit (run with --verbose for details).
   at: ObjectDB::cleanup (core\object.cpp:2070) - ObjectDB instances leaked at exit (run with --verbose for details).
ERROR: Resources still in use at exit (run with --verbose for details).
   at: ResourceCache::clear (core\resource.cpp:417) - Resources still in use at exit (run with --verbose for details).
```
It's related to https://github.com/godotengine/godot/issues/31378

I've splitted the plugin code into separate files and removed strong typing which caused troubles. It seems to be working fine.
https://github.com/sirmike/godothreadpool/commit/94bc585e4fe03df772b21902f870890056cd451c

If you're interested, please create a 3.x branch out of 1.1 tag and I'll create a PR with the changes.
I also think it is worth to add this version to Assets Library for Godot 3.x too. WDYT?

**Comment by zmarcos** [comment]
I think this is bad, but not bad enough for Godot developers to solve any time soon.

The workaround for this is very simple, seems good to me, you can send it to the **1.x** branch.

I can submit this version for Godot 3.x to the **Asset Library**, but I need to create a new entry.
**ThreadPool for Godot 3** or **ThreadPool 1** or **ThreadPool Classic** or **ThreadPool Legacy**, any preference?

**Comment by sirmike** [comment]
ThreadPool for Godot 3 sounds good. There are some addons with this naming convention already in the Library.

**Comment by zmarcos** [comment]
Alright, if everything goes well, soon we will get to see the addon on the Asset Library.
